frase = str(input('digite uma frase:')).strip().upper()
print('a frase tem ao todo {} letras'.format(len(frase)))
print('a letra A aparece {} vezes na frase'.format(frase.count('A')))
print('a primeira letra A aparece na posição {}'.format(frase.find('A') + 1))
print('a ultima letra A aparece na posição {}'.format(frase.rfind('A') + 1))
